CARD_NAME = "8Current"
VERSION = "0.1.0"

SLAVE_OWN_ADDRESS_BASE = 0x19
STACK_LEVEL_MAX = 7

CALIBRATION_KEY = 0xaa
RESET_CALIBRATION_KEY  = 0x55
WDT_RESET_SIGNATURE     = 0xca
WDT_RESET_COUNT_SIGNATURE    = 0xbe

VOLT_TO_MILIVOLT = 1000
MILIAMPER_TO_MICROAMPER = 1000

CRT_SCALE = 100

# i2c memory addresses
class I2C_MEM:
    LEDS = 0
    LED_SET = 1
    LED_CLR = 2
    CRT_IN_VAL = 3
    CRT_IN_RMS = 19
    CRT_SNS_RANGE = 35
    CRT_SNS_TYPE = 51

    CALIB_VALUE = 52
    CALIB_CHANNEL = 56
    CALIB_KEY = 57
    CALIB_STATUS = 58

    RTC_YEAR_ADD = 59
    RTC_MONTH_ADD = 60
    RTC_DAY_ADD = 61
    RTC_HOUR_ADD = 62
    RTC_MINUTE_ADD = 63
    RTC_SECOND_ADD = 64
    RTC_SET_YEAR_ADD = 65
    RTC_SET_MONTH_ADD = 66
    RTC_SET_DAY_ADD = 67
    RTC_SET_HOUR_ADD = 68
    RTC_SET_MINUTE_ADD = 69
    RTC_SET_SECOND_ADD = 70
    RTC_CMD_ADD = 71

    WDT_RESET_ADD = 72
    WDT_INTERVAL_SET_ADD = 73
    WDT_INTERVAL_GET_ADD = 75
    WDT_INIT_INTERVAL_SET_ADD = 77
    WDT_INIT_INTERVAL_GET_ADD = 79
    WDT_RESET_COUNT_ADD = 81
    WDT_CLEAR_RESET_COUNT_ADD = 83
    WDT_POWER_OFF_INTERVAL_SET_ADD = 84
    WDT_POWER_OFF_INTERVAL_GET_ADD = 88

    BUTTON = 92

    #DIAG_TEMPERATURE_ADD = 46
    DIAG_3V3_MV_ADD = 93
    DIAG_3V3_MV_ADD1 = 94

    REVISION_HW_MAJOR_ADD = 250
    REVISION_HW_MINOR_ADD = 251
    REVISION_MAJOR_ADD = 252
    REVISION_MINOR_ADD = 253

class CALIB:
    IN_PROGRESS = 0
    DONE = 1
    ERROR = 2
    CRT_IN_CH1 = 1

CHANNEL_NO = {
    "crt_in": 8,
    "led": 8,
}

